[package]
name = "tracing-json"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.202"
serde_json = "1.0.117"
tracing = "0.1.40"
tracing-core = "0.1.32"
tracing-serde = "0.1.3"
tracing-subscriber = "0.3.18"
