[package]
name = "json-subscriber"
version = "0.1.0"
edition = "2021"

[features]
default = []
tracing-log = ["tracing-subscriber/tracing-log", "dep:tracing-log"]
env-filter = ["tracing-subscriber/env-filter"]

[dependencies]
serde = "1.0.202"
serde_json = "1.0.117"
tracing = "0.1.40"
tracing-core = "0.1.32"
tracing-log = { version = "0.2.0", optional = true }
tracing-serde = "0.1.3"
tracing-subscriber = "0.3.18"

[dev-dependencies]
criterion = { version = "0.3.6", default-features = false }
tracing-subscriber = { version = "0.3", features = ["json"] }

[[bench]]
name = "tracing_subscriber"
harness = false
